ALTER TABLE voters ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE voters ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE voters ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE voters ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE voters ADD COLUMN IF NOT EXISTS booth_number INTEGER;
ALTER TABLE voters ADD COLUMN IF NOT EXISTS ward_number INTEGER;
ALTER TABLE voters ADD COLUMN IF NOT EXISTS election_id VARCHAR(255);
ALTER TABLE voters ADD COLUMN IF NOT EXISTS vote_status VARCHAR(50);